apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arb-harvester-keeper
  labels:
    app: arb-harvester-keeper
spec:
  schedule: "35 20 * * *"
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: arb-harvester-keeper
          containers:
          - name: arb-harvester-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.arbitrum_harvest"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
      backoffLimit: 3
