apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arb-vester-keeper
  labels:
    app: arb-vester-keeper
spec:
  schedule: "0 20 * * 4"
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: arb-vester-keeper
          containers:
          - name: arb-vester-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.arbitrum_tree_vest"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
      backoffLimit: 3
