apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eth-tender-keeper
  labels:
    app: eth-tender-keeper
spec:
  # cron to run every 30 min every day "*/30 * * * *"
  schedule: "30 9 * * 2,4,7"
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eth-tender-keeper
          containers:
          - name: eth-tender-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "scripts/eth_tend.py"]
            env:
              - name: LOG_LEVEL
                value: "info"
          restartPolicy: OnFailure
