apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eth-earner-keeper
  labels:
    app: eth-earner-keeper
spec:
  # cron to run every hour
  schedule: "10 * * * *"
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eth-earner-keeper
          containers:
          - name: eth-earner-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "scripts/eth_earn.py"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
