apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eth-bvecvx-earner-keeper
  labels:
    app: eth-bvecvx-earner-keeper
spec:
  schedule: "20 20 * * *"
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eth-bvecvx-earner-keeper
          containers:
          - name: eth-bvecvx-earner-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.earn_locked_cvx"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
