apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flashbots-harvester-keeper
  labels:
    app: flashbots-harvester-keeper
spec:
  schedule: "*/30 21-23,0-12 * * *"
  # schedule: "55 19 * * *"
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: flashbots-harvester-keeper
          containers:
          - name: flashbots-harvester-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "scripts/harvest_cvx.py"]
            #command: ["python", "scripts/one_time_harvests.py"]
            env:
              - name: LOG_LEVEL
                value: "info"
          restartPolicy: OnFailure
