apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ftm-harvester-keeper
  labels:
    app: ftm-harvester-keeper
spec:
  schedule: "13 0 * * 3"
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ftm-harvester-keeper
          containers:
          - name: ftm-harvester-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.ftm_harvest"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
      backoffLimit: 3
