apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ibbtc-fee-collector-keeper
  labels:
    app: ibbtc-fee-collector-keeper
spec:
  schedule: "20 17 * * *"
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ibbtc-fee-collector-keeper
          containers:
          - name: ibbtc-fee-collector-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.ibbtc_fees"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
