apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cake_harvester.yaml
<<<<<<< HEAD
  - general_harvester.yaml
=======
  - flashbots_harvester.yaml
>>>>>>> flashbots-harvest
  - ibbtc_fee_collector.yaml
  - propose_centralized_oracle.yaml
  - rebase.yaml
  - service.yaml
  - service_account.yaml