apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: propose-centralized-oracle-keeper
  labels:
    app: propose-centralized-oracle-keeper
spec:
  # cron to run at 2:30pm EST (cron in UTC time) every day "30 18 * * *"
  schedule: "30 18 * * *"
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: propose-centralized-oracle-keeper
          containers:
          - name: propose-centralized-oracle-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.propose_centralized_oracle"]
            env:
              - name: LOG_LEVEL
                value: 'info'
          restartPolicy: OnFailure
