apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rebase-keeper
  labels:
    app: rebase-keeper
spec:
  # cron to run at 4pm EST every day "0 20 * * *"
  schedule: "*/5 19,20 * * *"
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rebase-keeper
          containers:
          - name: rebase-keeper
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
            command: ["python", "-m", "scripts.rebase"]
            env:
              - name: LOG_LEVEL
                value: 'info'
              - name: GAS_LIMIT
                value: '12000000'
          restartPolicy: OnFailure
