apiVersion: v1
kind: Service
metadata:
  name: rebase-keeper
  labels:
    app: rebase-keeper
    service: rebase-keeper
spec:
  selector:
    app: rebase-keeper
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: propose-centralized-oracle-keeper
  labels:
    app: propose-centralized-oracle-keeper
    service: propose-centralized-oracle-keeper
spec:
  selector:
    app: propose-centralized-oracle-keeper
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: cake-harvester-keeper
  labels:
    app: cake-harvester-keeper
    service: cake-harvester-keeper
spec:
  selector:
    app: cake-harvester-keeper
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: ibbtc-fee-collector-keeper
  labels:
    app: ibbtc-fee-collector-keeper
    service: ibbtc-fee-collector-keeper
spec:
  selector:
    app: ibbtc-fee-collector-keeper
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: general-harvester-keeper
  labels:
    app: general-harvester-keeper
    service: general-harvester-keeper
spec:
  selector:
    app: general-harvester-keeper
  ports:
    - name: http
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: flashbots-harvester-keeper
  labels:
    app: flashbots-harvester-keeper
    service: flashbots-harvester-keeper
spec:
  selector:
    app: flashbots-harvester-keeper
  ports:
    - name: http
      port: 9000
---