apiVersion: v1
kind: ServiceAccount
metadata:
  name: arb-earner-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/arb-earner-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arb-harvester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/arb-harvester-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arb-vester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/arb-vester-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eth-bvecvx-earner-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/eth-bvecvx-earner-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eth-earner-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/eth-earner-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eth-vester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/eth-vester-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flashbots-harvester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/flashbots-harvester-keeper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent:flashbots-harvester-keeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: flashbots-harvester-keeper
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ftm-earner-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/ftm-earner-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ftm-harvester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/ftm-harvester-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibbtc-fee-collector-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/ibbtc-fee-collector-keeper
---
  