apiVersion: v1
kind: ServiceAccount
metadata:
  name: rebase-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/rebase-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/oracle-keeper
---