apiVersion: v1
kind: ServiceAccount
metadata:
  name: rebase-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/rebase-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: propose-centralized-oracle-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/propose-centralized-oracle-keeper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cake-harvester-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/cake-harvester-keeper
---
  apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibbtc-fee-collector-keeper
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::342684350154:role/ibbtc-fee-collector-keeper
---